kotlin.code.style=official

group=org.unbroken-dome.gradle-plugin-utils
version=0.5.0

projectName=Gradle Plugin Utilities
projectDescription=A collection of utilities for developing Gradle plugins
projectUrl=https://github.com/unbroken-dome/gradle-plugin-utils
projectLicenseName=The MIT License (MIT)
projectLicenseUrl=https://mit-license.org

githubRepo=unbroken-dome/gradle-plugin-utils

dokkaVersion=1.8.20
org.gradle.jvmargs=-Xmx1024m
